### ISSUE TITLE
Change Behavior for Declaration of Multiple Unnamed Link Types Over the Same Path

### ISSUE THREAD

**Issue by stojimirovic** [AelasticS/aelastics#11]
**Current Behavior**:
When two LinkType types are declared with the same path, they are treated as independent types, even though they share the same path. For example:

```javascript
const LinkA = t.link('/path/to/resource');
const LinkB = t.link('/path/to/resource');
```
Currently, LinkA and LinkB are treated as distinct, independent types, even though they share the same path (/path/to/resource).

**Proposed Change**:
The new behavior should be as follows:

When two LinkType types are declared with the same path, only one LinkType should be created, rather than creating two independent types.

For example:

```javascript
const LinkA = t.link('/path/to/resource');
const LinkB = t.link('/path/to/resource');
```
Both LinkA and LinkB should refer to the same type t.link('/path/to/resource').

When the paths differ or when the LinkType types are given distinct names, separate LinkType types should still be created. For example:

If the paths differ:

```javascript
const LinkA = t.link('/path/to/resourceA');
const LinkB = t.link('/path/to/resourceB');
```
LinkA and LinkB should be independent types because their paths differ (/path/to/resourceA vs /path/to/resourceB).

If the LinkType types have the same path but different names:

```javascript
const LinkA = t.link('/path/to/resource', 'LinkTypeA');
const LinkB = t.link('/path/to/resource', 'LinkTypeB');
```
LinkA and LinkB should be treated as independent types because they have distinct names, even though they share the same path (/path/to/resource).

**Benefits**:
This change will reduce duplication of types when multiple LinkType types with the same path are defined. It will lead to a cleaner and more efficient type system, especially in larger codebases where many LinkType types with the same path are declared.

**Impact**:
The behavior of LinkType resolution will change, potentially affecting existing code that relies on distinct LinkType types with the same path. However, this change is expected to improve consistency and reduce redundancy in type definitions.

**Next Steps**:
Review and discuss the proposed change.
Determine if any breaking changes are anticipated and outline migration steps if necessary.

**Comment by Sinisa-Neskovic** [comment]
@stojimirovic The part in the issue text where the function example should be corrected.": t.link(**schema**, '/path/to/resource', 'LinkTypeA');
